apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    app: flask-app
spec:
  containers:
    - name: flask-container
      image: 315510/flask-hello-world:latest
      ports:
        - containerPort: 8000
